name: 'Electron Build and Test'
description: 'It builds and tests an Electron App on all 3 Platforms'
author: 'Sebastian Schuchmann'

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@master
      uses: actions/setup-node@master
      with:
        version: 10.x
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
